name: domain
description: Helper package to handle domain and business logic.
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Value equality
  equatable: ^2.0.3
  # UUID
  uuid: ^3.0.4

dev_dependencies:
  very_good_analysis: ^3.0.1
